### ISSUE TITLE
Maybe make it compatible with the light mode?

### ISSUE THREAD

**Issue by ivan123-tty** [aragubas/Aragubas-DiscordTheme#1]
It looks weird with the light mode enabled.
![KzbVrBb0c6](https://user-images.githubusercontent.com/70339505/158192248-1b3edd34-8f43-47c5-8b27-b5a3baebc751.png)
![HLVY81Drs0](https://user-images.githubusercontent.com/70339505/158192253-f00a4f7b-f92f-48a9-81a5-78378b2eab9d.png)

**Comment by aragubas** [comment]
Working on it!!

**Comment by aragubas** [comment]
Done!, Added support for white theme!
